const initialState = {
  searchUnpublishArticle: "",
  searchReviewArticle: "",
  searchReadyArticle: "",
  popUpState: 0,
  showFormResponse: false,
  getVolumeData: {
    selectedVolume: "Select Volume",
    selectedIssue: "Select Issue",
    selectedIssueType: "",
    selectedDate: "",
  },
  createdNewVol: false,
  newVolumeCreated: {
    volumeNumber: "",
    issue: "",
  },
  articleData: {
    status: "review",
    authorDetails: {
      primary: {
        name: "",
        email: "",
        phone: "",
        affiliation: "",
        country: "",
      },
      secondaryAuthors: [],
    },
    title: "",
    abstract: "",
    keywords: [],
    primaryAuthor: "",
    secondaryAuthors: [],
    day: "",
    month: "",
    year: "",
    volume: "",
    issueType: "",
    issue: "",
    startPage: "",
    endPage: "",
  },
  formIndex: 0,
  totalPage: "",
  publishArticleData: "",
  finalFile: "",
  oldArticleId: "",
  notification: {
    message: "",
    sent: false,
    status: "success",
  },
  specialIssue: false,
  responseText: "",
  popupResponse: false,
  searchArticleId: "",
  invalidFile: false,
};

export default initialState;
